workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios && pod install --repo-update && cd ..
      - name: Build iOS app
        script: |
          flutter build ios --release --no-codesign
      - name: Create IPA
        script: |
          flutter build ipa --export-options-plist=ios/exportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/ipa/*.app.dSYM.zip
        skip_metadata: true
        skip_screenshots: true
