source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
enable_bitcode = false
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\s*?=\s*?(?<path>\S+)/)
    return matches[:path] if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  platform :ios, '13.0'

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

  # Add Firebase pods
  pod 'Firebase/Auth', '~> 10.25.0'
  pod 'Firebase/Core', '~> 10.25.0'
  pod 'Firebase/Firestore', '~> 10.25.0'
  pod 'GoogleSignIn', '~> 8.0'
  pod 'GoogleUtilities/Environment', '~> 7.11'
  pod 'GoogleUtilities/UserDefaults', '~> 7.11'
  pod 'GoogleUtilities/Logger', '~> 7.11'
  pod 'GoogleUtilities/Network', '~> 7.11'
  pod 'GoogleUtilities/Reachability', '~> 7.11'
  pod 'GoogleUtilities/NSData+zlib', '~> 7.11'
  pod 'GoogleUtilities/MethodSwizzler', '~> 7.11'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = enable_bitcode
    end
  end
end
